// LOCALHOST 
### 
GET http://localhost:8080/contacts 
### 
GET http://localhost:8080/contacts/632b21c3bc63158a737c1f0b 
### 
GET http://localhost:8080/contacts/632b223cbc63158a737c1f0c 
### 
GET http://localhost:8080/contacts/632b2297bc63158a737c1f0d

// PRODUCTION Deploy ### GET https://cse341-instructor.herokuapp.com/contacts ### GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2 ### GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3 ### GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4