// LOCALHOST 
### 
GET http://localhost:8080/contacts 
### 
GET http://localhost:8080/contacts/632b21c3bc63158a737c1f0b 
### 
GET http://localhost:8080/contacts/632b223cbc63158a737c1f0c 
### 
GET http://localhost:8080/contacts/632b2297bc63158a737c1f0d

// PRODUCTION Deploy 
### 
GET https://jw-341-projectone.onrender.com/contacts 
### 
GET https://jw-341-projectone.onrender.com/contacts/632b21c3bc63158a737c1f0b 
### 
GET https://jw-341-projectone.onrender.com/contacts/632b223cbc63158a737c1f0c 
### 
GET https://jw-341-projectone.onrender.com/contacts/632b2297bc63158a737c1f0d